### ISSUE TITLE
requirements.txt not present

### ISSUE THREAD

**Issue by nutansah00** [lightmatmul/Transformer-from-scratch#1]
Hi, in the readme it is mentioned that required packages can be installed by using `pip install -r requirements.txt`, however this file is not present in the repo.

**Comment by lightmatmul** [comment]
oh wow, did not expect anyone to come check out my repos, many thanks for your interest @nutansah00 .. indeed, I am very sorry for this. Actually, there is only one package to install which is torch, so `pip install torch` should do the trick !

I just updated the installation steps in the readme.md, hopefully this works for you. Keep me posted.
